name: Release Gem

on:
  push:
    paths:
      - 'lib/hermod/version.rb'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test
        run: bundle exec rake

      - name: Check for pre-release
        id: is_prerelease
        run: echo "is_prerelease=$(ruby -e 'puts Gem::Specification.load("hermod.gemspec").version.prerelease?')" >> "$GITHUB_OUTPUT"

      - name: Create a Pre-release
        if: ${{ github.ref != 'refs/heads/master' && steps.is_prerelease.outputs.is_prerelease == 'true' }}
        uses: rubygems/release-gem@v1

      - name: Create a Release
        if: ${{ github.ref == 'refs/heads/master' && steps.is_prerelease.outputs.is_prerelease == 'false' }}
        uses: rubygems/release-gem@v1
