name: Release Gem

on:
  push:
    paths:
      - 'lib/hermod/version.rb'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          bundler-cache: true

      - name: Test
        run: bundle exec rake

      - name: Check for pre-release
        id: is_prerelease
        run: echo "is_prerelease=$(ruby -e 'puts Gem::Specification.load("hermod.gemspec").version.prerelease?')" >> "$GITHUB_OUTPUT"

      - name: Create a Pre-release
        if: ${{ github.ref != 'refs/heads/master' && steps.is_prerelease.outputs.is_prerelease == 'true' }}
        uses: rubygems/release-gem@7f9650160c1a4e7989fdc9855807bdbd421d8b6b # v1

      - name: Create a Release
        if: ${{ github.ref == 'refs/heads/master' && steps.is_prerelease.outputs.is_prerelease == 'false' }}
        uses: rubygems/release-gem@7f9650160c1a4e7989fdc9855807bdbd421d8b6b # v1
