name: reviewdog
on: [pull_request]
jobs:
  actionlint:
    name: runner / actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actionlint
        uses: reviewdog/action-actionlint@v1.2.0
        with:
          fail_on_error: true
          reporter: github-pr-review
